### ISSUE TITLE
invalid syntax "match splits:" in "comfyui_primitive_ops.py", line 280

### ISSUE THREAD

**Issue by IOZZYS** [jamesWalker55/comfyui-various#10]
Traceback (most recent call last):

  File "/home/user/data/applications/ComfyUI/nodes.py", line 1994, in load_custom_node
    module_spec.loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/data/applications/ComfyUI/custom_nodes/comfyui-various/__init__.py", line 77, in <module>
    load_nodes(module_name)

  File "/home/user/data/applications/ComfyUI/custom_nodes/comfyui-various/__init__.py", line 42, in load_nodes
    module = importlib.import_module(module_name, package=__name__)

  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/home/user/data/applications/ComfyUI/custom_nodes/comfyui-various/comfyui_primitive_ops.py", line 280
    match splits:
          ^
SyntaxError: invalid syntax

Cannot import /home/user/data/applications/ComfyUI/custom_nodes/comfyui-various module for custom nodes: invalid syntax (comfyui_primitive_ops.py, line 280)

**Comment by jamesWalker55** [comment]
Please upgrade your Python to version 3.10 or above
