### ISSUE TITLE
AssertionError with Image Flip

### ISSUE THREAD

**Issue by g558800** [jamesWalker55/comfyui-various#9]
Traceback (most recent call last):
  File "H:\AI\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\AI\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\AI\ComfyUI\custom_nodes\comfyui_image_ops.py", line 315, in execute
    assert direction in ("horizontal", "vertical")
AssertionError

**Comment by jamesWalker55** [comment]
Should be fixed with cc66b62c0861314a4952eb96a6ae330f180bf6a1, please update the extension and re-create the node then it should work again.
